@echo off
cd /d C:\u-blox\ucx-web-app\ucx-web-app\build
set EMSDK=C:/u-blox/ucx-web-app/emsdk
set EMSDK_NODE=C:\u-blox\ucx-web-app\emsdk\node\22.16.0_64bit\bin\node.exe
set EMSDK_PYTHON=C:\u-blox\ucx-web-app\emsdk\python\3.13.3_64bit\python.exe
set PATH=C:\u-blox\ucx-web-app\emsdk;C:\u-blox\ucx-web-app\emsdk\upstream\emscripten;C:\u-blox\ucx-web-app\emsdk\node\22.16.0_64bit\bin;%PATH%

C:\u-blox\ucx-web-app\emsdk\python\3.13.3_64bit\python.exe C:\u-blox\ucx-web-app\emsdk\upstream\emscripten\emcc.py -O3 -DNDEBUG -s WASM=1 -s MODULARIZE=1 -s EXPORT_NAME=createUCXModule -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=16777216 -O2 --no-entry CMakeFiles/ucxclient.dir/u_port_web.c.o CMakeFiles/ucxclient.dir/ucx_wasm_wrapper.c.o "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/src/u_cx_at_client.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/src/u_cx_at_params.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/src/u_cx_at_urc_queue.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/src/u_cx_at_util.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/src/u_cx_log.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/src/u_cx_xmodem.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_bluetooth.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_diagnostics.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_error_codes.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_gatt_client.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_gatt_server.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_general.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_http.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_mqtt.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_network_time.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_power.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_security.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_socket.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_sps.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_system.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_urc.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/generated/NORA-W36X/u_cx_wifi.c.o" "CMakeFiles/ucxclient.dir/C_/u-blox/ucx-web-app/ucxclient/ucx_api/u_cx.c.o" -o test_direct.js
echo.
echo Exit code: %ERRORLEVEL%
pause
