// Auto-generated UCX API wrapper P/Invoke declarations
// DO NOT EDIT - Generated by generate_wrapper.py

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace UcxAvaloniaApp.Services
{
    public static partial class UcxNativeGenerated
    {
        private const string DllName = "ucxclient_wrapper";

        #region BLUETOOTH Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetMode(IntPtr instance, int mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetMode(IntPtr instance, out int pMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_Connect(IntPtr instance, out int bd_addr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_Disconnect(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_GetLocalNameBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ppDeviceName);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetLocalName(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string device_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_DiscoveryDefaultBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_DiscoveryDefaultGetNext(IntPtr instance, out int pBtDiscoveryDefaultRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_Discovery1Begin(IntPtr instance, int discovery_type);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_Discovery1GetNext(IntPtr instance, out int pBtDiscoveryRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_Discovery2Begin(IntPtr instance, int discovery_type, int discovery_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_Discovery2GetNext(IntPtr instance, out int pBtDiscoveryRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_Discovery3Begin(IntPtr instance, int discovery_type, int discovery_mode, int discovery_length);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_Discovery3GetNext(IntPtr instance, out int pBtDiscoveryRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_BgDiscoveryDefaultStart(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_BgDiscoveryStart1(IntPtr instance, int discovery_type);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_BgDiscoveryStart2(IntPtr instance, int discovery_type, int discovery_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_BgDiscoveryStart3(IntPtr instance, int discovery_type, int discovery_mode, int output_events);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_BgDiscoveryStop(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetRssi(IntPtr instance, int conn_handle, out int pRssi);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_ListConnectionsBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_ListConnectionsGetNext(IntPtr instance, out int pBtListConnectionsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_ListConnectionStatusBegin(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_ListConnectionStatusGetNext(IntPtr instance, out int pBtListConnectionStatusRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetConnectionStatus(IntPtr instance, int conn_handle, int prop_id, out int pStatusVal);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetAdvertiseInformation(IntPtr instance, out int pBtGetAdvertiseInformationRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetLegacyAdvertiseData(IntPtr instance, IntPtr adv_data, int adv_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_GetLegacyAdvertiseDataBegin(IntPtr instance, out int pAdvData);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_ClearLegacyAdvertiseData(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetScanResponseData(IntPtr instance, IntPtr scan_rsp_data, int scan_rsp_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_GetScanResponseDataBegin(IntPtr instance, out int pScanRspData);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_ClearScanResponseData(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_LegacyAdvertisementStart(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_LegacyAdvertisementStop(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_DirectedAdvertisementStart1(IntPtr instance, out int bd_addr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_DirectedAdvertisementStart2(IntPtr instance, out int bd_addr, int timeout);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_DirectedAdvertisementStop(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetConnectionIntervalMin(IntPtr instance, int connection_interval_minimum);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetConnectionIntervalMin(IntPtr instance, out int pConnectionIntervalMinimum);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetConnectionIntervalMax(IntPtr instance, int connection_interval_maximum);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetConnectionIntervalMax(IntPtr instance, out int pConnectionIntervalMaximum);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetConnectionPeripheralLatency(IntPtr instance, int connection_peripheral_latency);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetConnectionPeripheralLatency(IntPtr instance, out int pConnectionPeripheralLatency);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetConnectionLinklossTimeout(IntPtr instance, int connection_linkloss_timeout);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetConnectionLinklossTimeout(IntPtr instance, out int pConnectionLinklossTimeout);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetPreferredTxPhy(IntPtr instance, int preferred_tx_phy);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetPreferredTxPhy(IntPtr instance, out int pPreferredTxPhy);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetPreferredRxPhy(IntPtr instance, int preferred_rx_phy);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetPreferredRxPhy(IntPtr instance, out int pPreferredRxPhy);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetLegacyAdvertisementConfig(IntPtr instance, int advertisement_interval_minimum, int advertisement_interval_maximum);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetLegacyAdvertisementConfig(IntPtr instance, out int pBtGetLegacyAdvertisementConfigRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetScanInterval(IntPtr instance, int scan_interval);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetScanInterval(IntPtr instance, out int pScanInterval);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetScanWindow(IntPtr instance, int scan_window);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetScanWindow(IntPtr instance, out int pScanWindow);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetConnectToDirectedAdv(IntPtr instance, int connect_to_directed_adv);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetConnectToDirectedAdv(IntPtr instance, out int pConnectToDirectedAdv);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetIoCapabilities(IntPtr instance, int io_cap);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetIoCapabilities(IntPtr instance, out int pIoCap);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetSecurityMode(IntPtr instance, int security_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetSecurityMode(IntPtr instance, out int pSecurityMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetPairingMode(IntPtr instance, int pairing_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetPairingMode(IntPtr instance, out int pPairingMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_UserConfirmation(IntPtr instance, out int bd_addr, int confirm);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_UserPasskeyEntry2(IntPtr instance, out int bd_addr, int confirm);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_UserPasskeyEntry3(IntPtr instance, out int bd_addr, int confirm, int passkey);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_Bond(IntPtr instance, out int bd_addr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_Unbond(IntPtr instance, out int bd_addr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_UnbondAll(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_ListBondedDevicesBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_ListBondedDevicesGetNext(IntPtr instance, out int pBdAddr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetDeviceInfoServiceChar(IntPtr instance, int char_id, [MarshalAs(UnmanagedType.LPStr)] string char_value);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_GetDeviceInfoServiceCharBegin(IntPtr instance, int char_id, [MarshalAs(UnmanagedType.LPStr)] string ppCharValue);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_ListDeviceInfoServiceCharsBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_ListDeviceInfoServiceCharsGetNext(IntPtr instance, out int pBtListDeviceInfoServiceCharsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_RequestPhy(IntPtr instance, int conn_handle, int tx_phy, int rx_phy);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetPhy(IntPtr instance, int conn_handle, out int pBtGetPhyRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterConnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterDisconnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterBondStatus(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterUserConfirmation(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterPasskeyEntry(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterPasskeyRequest(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterPhyUpdate(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_RegisterBackgroundDiscovery(IntPtr instance, int callback);

        #endregion

        #region DIAGNOSTICS Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Ping1(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string destination);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Ping2(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string destination, int count);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_PingStop(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf2(IntPtr instance, int iperf_action, int protocol_type);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf5(IntPtr instance, int iperf_action, int protocol_type, int role, int port, int report_interval);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf7(IntPtr instance, int iperf_action, int protocol_type, int role, int port, int report_interval, int time_boundary, out int ip_addr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf8(IntPtr instance, int iperf_action, int protocol_type, int role, int port, int report_interval, int time_boundary, out int ip_addr, int length);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf9(IntPtr instance, int iperf_action, int protocol_type, int role, int port, int report_interval, int time_boundary, out int ip_addr, int length, int bandwidth);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf10(IntPtr instance, int iperf_action, int protocol_type, int role, int port, int report_interval, int time_boundary, out int ip_addr, int length, int bandwidth, int bidirectional);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_diagnostics_RegisterPingComplete(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_diagnostics_RegisterPingResponse(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_diagnostics_RegisterIperfOutput(IntPtr instance, int callback);

        #endregion

        #region GATT_CLIENT Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverPrimaryServicesBegin(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverPrimaryServicesGetNext(IntPtr instance, out int pGattClientDiscoverPrimaryServicesRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverPrimaryServicesByUuidBegin(IntPtr instance, int conn_handle, IntPtr uuid, int uuid_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverPrimaryServicesByUuidGetNext(IntPtr instance, out int pGattClientDiscoverPrimaryServicesByUuidRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverServiceCharsBegin(IntPtr instance, int conn_handle, int start, int end);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverServiceCharsGetNext(IntPtr instance, out int pGattClientDiscoverServiceCharsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverCharDescriptorsBegin(IntPtr instance, int conn_handle, int value_handle, int char_end_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverCharDescriptorsGetNext(IntPtr instance, out int pGattClientDiscoverCharDescriptorsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_ReadBegin(IntPtr instance, int conn_handle, int value_handle, out int pHexData);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_ReadByUuidBegin(IntPtr instance, int conn_handle, int start, int end, IntPtr uuid, int uuid_len, out int pGattClientReadByUuidRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_client_Write(IntPtr instance, int conn_handle, int value_handle, IntPtr hex_data, int hex_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_client_ConfigWrite(IntPtr instance, int conn_handle, int desc_handle, int config);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_client_WriteNoRsp(IntPtr instance, int conn_handle, int value_handle, IntPtr hex_data, int hex_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_client_WriteLong(IntPtr instance, int conn_handle, int value_handle, IntPtr hex_data, int hex_data_len, int reliable, int flag, int offset);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_RegisterNotification(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_RegisterIndication(IntPtr instance, int callback);

        #endregion

        #region GATT_SERVER Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_ServiceDefine(IntPtr instance, IntPtr uuid, int uuid_len, out int pSerHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_CharDefine5(IntPtr instance, IntPtr uuid, int uuid_len, IntPtr properties, int properties_len, int read_security, int write_security, IntPtr value, int value_len, out int pGattServerCharDefineRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_CharDefine6(IntPtr instance, IntPtr uuid, int uuid_len, IntPtr properties, int properties_len, int read_security, int write_security, IntPtr value, int value_len, int max_length, out int pGattServerCharDefineRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_HostCharDefine(IntPtr instance, IntPtr uuid, int uuid_len, IntPtr properties, int properties_len, int read_security, int write_security, out int pGattServerHostCharDefineRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_DescriptorDefine4(IntPtr instance, IntPtr uuid, int uuid_len, int read_security, int write_security, IntPtr value, int value_len, out int pDescHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_DescriptorDefine5(IntPtr instance, IntPtr uuid, int uuid_len, int read_security, int write_security, IntPtr value, int value_len, int max_length, out int pDescHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_ServiceActivate(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_ReadReqResponse(IntPtr instance, int conn_handle, IntPtr value, int value_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_SendNotification(IntPtr instance, int conn_handle, int char_handle, IntPtr value, int value_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_SendIndication(IntPtr instance, int conn_handle, int char_handle, IntPtr value, int value_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_SetAttrValue(IntPtr instance, int attr_handle, IntPtr value, int value_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_ReadReqError(IntPtr instance, int conn_handle, IntPtr error_code, int error_code_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_WriteReqError(IntPtr instance, int conn_handle, IntPtr error_code, int error_code_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_WriteReqResponse(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_SendServiceChangedInd(IntPtr instance, int conn_handle, int start_handle, int end_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_server_RegisterNotification(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_server_RegisterReadAttribute(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_server_RegisterIndicationAck(IntPtr instance, int callback);

        #endregion

        #region GENERAL Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_general_Attention(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetManufacturerIdentificationBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ppManufacturer);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetDeviceModelIdentificationBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ppDeviceModel);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetSoftwareVersionBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ppVersion);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetSerialNumberBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ppSerialNumber);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetIdentInfoBegin(IntPtr instance, out int pGeneralGetIdentInfoRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetTypeCodeBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ppTypeCode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_general_SetGreetingText1(IntPtr instance, int greeting_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_general_SetGreetingText2(IntPtr instance, int greeting_mode, [MarshalAs(UnmanagedType.LPStr)] string text);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetGreetingTextBegin(IntPtr instance, out int pGeneralGetGreetingTextRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_general_RegisterStartup(IntPtr instance, int callback);

        #endregion

        #region HTTP Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetConnectionParams2(IntPtr instance, int session_id, [MarshalAs(UnmanagedType.LPStr)] string host);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetConnectionParams3(IntPtr instance, int session_id, [MarshalAs(UnmanagedType.LPStr)] string host, int port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetTLS2(IntPtr instance, int session_id, int tls_version);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetTLS3(IntPtr instance, int session_id, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetTLS5(IntPtr instance, int session_id, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name, [MarshalAs(UnmanagedType.LPStr)] string client_cert_name, [MarshalAs(UnmanagedType.LPStr)] string client_key_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetTLSBegin(IntPtr instance, int session_id, out int pHttpGetTLSRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_Disconnect(IntPtr instance, int session_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetHeader1Begin(IntPtr instance, int session_id, out int pHttpGetHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetHeader2Begin(IntPtr instance, int session_id, int data_length, out int pHttpGetHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_GetBody(IntPtr instance, int session_id, int data_length, out byte pDataBuf, out int pMoreToRead);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_AddHeaderField(IntPtr instance, int session_id, [MarshalAs(UnmanagedType.LPStr)] string field_name, [MarshalAs(UnmanagedType.LPStr)] string field_value);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetCustomHeader(IntPtr instance, int session_id, [MarshalAs(UnmanagedType.LPStr)] string header_data);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_ClearHeaderCustom(IntPtr instance, int session_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetRequestPath(IntPtr instance, int session_id, [MarshalAs(UnmanagedType.LPStr)] string path);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetRequestPathBegin(IntPtr instance, int session_id, out int pHttpGetRequestPathRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_GetRequest(IntPtr instance, int session_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetGetRequestHeaderBegin(IntPtr instance, int session_id, out int pHttpGetGetRequestHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_DeleteRequest1(IntPtr instance, int session_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_DeleteRequest2(IntPtr instance, int session_id, [MarshalAs(UnmanagedType.LPStr)] string byte_array_data, int byte_array_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetDeleteRequestHeaderBegin(IntPtr instance, int session_id, out int pHttpGetDeleteRequestHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_PostRequest(IntPtr instance, int session_id, IntPtr binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetPostRequestHeaderBegin(IntPtr instance, int session_id, out int pHttpGetPostRequestHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_PutRequest(IntPtr instance, int session_id, IntPtr binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetPutRequestHeaderBegin(IntPtr instance, int session_id, out int pHttpGetPutRequestHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_http_RegisterDisconnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_http_RegisterRequestStatus(IntPtr instance, int callback);

        #endregion

        #region MQTT Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams3(IntPtr instance, int mqtt_id, [MarshalAs(UnmanagedType.LPStr)] string hostname, int port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams4(IntPtr instance, int mqtt_id, [MarshalAs(UnmanagedType.LPStr)] string hostname, int port, [MarshalAs(UnmanagedType.LPStr)] string client_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams5(IntPtr instance, int mqtt_id, [MarshalAs(UnmanagedType.LPStr)] string hostname, int port, [MarshalAs(UnmanagedType.LPStr)] string client_id, [MarshalAs(UnmanagedType.LPStr)] string username);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams6(IntPtr instance, int mqtt_id, [MarshalAs(UnmanagedType.LPStr)] string hostname, int port, [MarshalAs(UnmanagedType.LPStr)] string client_id, [MarshalAs(UnmanagedType.LPStr)] string username, [MarshalAs(UnmanagedType.LPStr)] string password);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_mqtt_GetConnectionParamsBegin(IntPtr instance, int mqtt_id, out int pMqttGetConnectionParamsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_Connect(IntPtr instance, int mqtt_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetKeepAlive(IntPtr instance, int mqtt_id, int keep_alive);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_GetKeepAlive(IntPtr instance, int mqtt_id, out int pKeepAlive);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetLastWillAndTestament3(IntPtr instance, int mqtt_id, [MarshalAs(UnmanagedType.LPStr)] string topic, [MarshalAs(UnmanagedType.LPStr)] string will_msg);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetLastWillAndTestament4(IntPtr instance, int mqtt_id, [MarshalAs(UnmanagedType.LPStr)] string topic, [MarshalAs(UnmanagedType.LPStr)] string will_msg, int qos);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetLastWillAndTestament5(IntPtr instance, int mqtt_id, [MarshalAs(UnmanagedType.LPStr)] string topic, [MarshalAs(UnmanagedType.LPStr)] string will_msg, int qos, int retain);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_mqtt_GetLastWillAndTestamentBegin(IntPtr instance, int mqtt_id, out int pMqttGetLastWillAndTestamentRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetTLS2(IntPtr instance, int mqtt_id, int tls_version);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetTLS3(IntPtr instance, int mqtt_id, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetTLS5(IntPtr instance, int mqtt_id, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name, [MarshalAs(UnmanagedType.LPStr)] string client_cert_name, [MarshalAs(UnmanagedType.LPStr)] string client_key_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_mqtt_GetTLSBegin(IntPtr instance, int mqtt_id, out int pMqttGetTLSRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_Disconnect(IntPtr instance, int mqtt_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_Publish(IntPtr instance, int mqtt_id, int qos, int retain, [MarshalAs(UnmanagedType.LPStr)] string topic, IntPtr binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_Subscribe3(IntPtr instance, int mqtt_id, int subscribe_action, [MarshalAs(UnmanagedType.LPStr)] string topic);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_Subscribe4(IntPtr instance, int mqtt_id, int subscribe_action, [MarshalAs(UnmanagedType.LPStr)] string topic, int qos);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_ReadBegin(IntPtr instance, int mqtt_id, out byte pDataBuf, ushort dataBufLength, [MarshalAs(UnmanagedType.LPStr)] string ppTopic);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_mqtt_RegisterConnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_mqtt_RegisterDisconnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_mqtt_RegisterDataAvailable(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_mqtt_RegisterDataDropped(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_mqtt_RegisterPublishCompleted(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_mqtt_RegisterSubscribeCompleted(IntPtr instance, int callback);

        #endregion

        #region NETWORK_TIME Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_network_time_SetClientEnabled(IntPtr instance, int client_status);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_network_time_GetClientEnabled(IntPtr instance, out int pClientStatus);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_network_time_SetNtpServer(IntPtr instance, int ntp_server_id, [MarshalAs(UnmanagedType.LPStr)] string ntp_server_address);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_network_time_GetNtpServerBegin(IntPtr instance, out int pNtpGetNtpServerRsp);

        #endregion

        #region POWER Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_DeepSleepWithGpioWakeup(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_DeepSleep(IntPtr instance, int wakeup_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_SetPowerSaveLevel(IntPtr instance, int level);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_GetPowerSaveLevel(IntPtr instance, out int pLevel);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_SetPowerSaveTimeout(IntPtr instance, int timeoutMs);

        #endregion

        #region SECURITY Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateRemove(IntPtr instance, int cert_type, [MarshalAs(UnmanagedType.LPStr)] string name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateRemoveAll(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateUpload(IntPtr instance, int cert_type, [MarshalAs(UnmanagedType.LPStr)] string name, IntPtr binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateUploadPW(IntPtr instance, int cert_type, [MarshalAs(UnmanagedType.LPStr)] string name, [MarshalAs(UnmanagedType.LPStr)] string password, IntPtr binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_security_ListCertificatesBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ListCertificatesGetNext(IntPtr instance, out int pSecListCertificatesRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ReadAllCertificatesDetailsBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string name, out int pSecReadAllCertificatesDetailsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ReadCertificatesDetailsBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string name, int cert_detail_id, out int pSecReadCertificatesDetailsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_security_ListTlsExtensionsBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ListTlsExtensionsGetNext(IntPtr instance, out int pSecListTlsExtensionsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_SetTlsServerNameIndication(IntPtr instance, int enabled);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_GetTlsServerNameIndication(IntPtr instance, out int pEnabled);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_SetTlsHandshakeFrag(IntPtr instance, int enabled);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_GetTlsHandshakeFrag(IntPtr instance, out int pEnabled);

        #endregion

        #region SOCKET Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Create1(IntPtr instance, int protocol, out int pSocketHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Create2(IntPtr instance, int protocol, int pref_ip_ver, out int pSocketHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetTLS2(IntPtr instance, int socket_handle, int tls_version);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetTLS3(IntPtr instance, int socket_handle, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetTLS5(IntPtr instance, int socket_handle, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name, [MarshalAs(UnmanagedType.LPStr)] string client_cert_name, [MarshalAs(UnmanagedType.LPStr)] string client_key_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_socket_GetTLSBegin(IntPtr instance, int socket_handle, out int pSocketGetTLSRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Connect(IntPtr instance, int socket_handle, [MarshalAs(UnmanagedType.LPStr)] string host_address, int remote_port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetReadMode(IntPtr instance, int read_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_GetReadMode(IntPtr instance, out int pReadMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Write(IntPtr instance, int socket_handle, IntPtr binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Close(IntPtr instance, int socket_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Read(IntPtr instance, int socket_handle, int length, out byte pDataBuf);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_GetLastError(IntPtr instance, out int pErrorCode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Bind(IntPtr instance, int socket_handle, int local_port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Listen1(IntPtr instance, int socket_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Listen2(IntPtr instance, int socket_handle, int port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_ReceiveFrom(IntPtr instance, int socket_handle, int length, out byte pDataBuf, out int pSocketReceiveFromRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_GetPeerAddress(IntPtr instance, int socket_handle, out int pSocketGetPeerAddressRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_socket_ListStatusBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_socket_ListStatusGetNext(IntPtr instance, out int pSocketListStatusRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_GetStatus(IntPtr instance, int socket_handle, out int pSocketGetStatusRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetOption(IntPtr instance, int socket_handle, int option, int value);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_GetOption(IntPtr instance, int socket_handle, int option, out int pValue);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_GetHostByName(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string host_name, out int pHostIp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_socket_RegisterConnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_socket_RegisterDataAvailable(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_socket_RegisterClosed(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_socket_RegisterIncomingConnection(IntPtr instance, int callback);

        #endregion

        #region SPS Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Connect1(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Connect2(IntPtr instance, int conn_handle, int flow_control);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_SetServiceEnable(IntPtr instance, int service_option);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_GetServiceEnable(IntPtr instance, out int pServiceOption);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Write(IntPtr instance, int conn_handle, IntPtr binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_SetDataMode(IntPtr instance, int read_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_GetDataMode(IntPtr instance, out int pReadMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Read(IntPtr instance, int conn_handle, int length, out byte pDataBuf);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_sps_RegisterConnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_sps_RegisterDisconnect(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_sps_RegisterDataAvailable(IntPtr instance, int callback);

        #endregion

        #region SYSTEM Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_Reboot(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartSerialFirmwareUpdate1(IntPtr instance, int baud_rate);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartSerialFirmwareUpdate2(IntPtr instance, int baud_rate, int flow_control);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartSerialFirmwareUpdateDefault(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartBootLoader1(IntPtr instance, int baud_rate);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartBootLoader2(IntPtr instance, int baud_rate, int flow_control);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartBootLoaderDefault(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StoreConfiguration(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetLocalAddress(IntPtr instance, int interface_id, out int pAddress);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetLocalAddress(IntPtr instance, int interface_id, out int address);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_FactoryReset(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_DefaultSettings(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetUartSettings1(IntPtr instance, int baud_rate);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetUartSettings2(IntPtr instance, int baud_rate, int flow_control);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetUartSettings3(IntPtr instance, int baud_rate, int flow_control, int change_after_confirm);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetUartSettings(IntPtr instance, out int pSysGetUartSettingsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetLastErrorCode(IntPtr instance, out int pErrorCode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetExtendedError(IntPtr instance, int extended_errors);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetExtendedError(IntPtr instance, out int pExtendedErrors);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetUnixTime(IntPtr instance, IntPtr unix_time, int unix_time_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_system_GetUnixTimeBegin(IntPtr instance, out int pUnixTime);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetEchoOff(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetEchoOn(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetEcho(IntPtr instance, out int pEchoOn);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetEscSequenceChar(IntPtr instance, int escape_char);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetEscSequenceChar(IntPtr instance, out int pEscapeChar);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetLineTermChar(IntPtr instance, int line_term);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetLineTermChar(IntPtr instance, out int pLineTerm);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetRspFormatChar(IntPtr instance, int resp_format);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetRspFormatChar(IntPtr instance, out int pRespFormat);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetBackspaceChar(IntPtr instance, int backspace);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetBackspaceChar(IntPtr instance, out int pBackspace);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetEscSequenceSettings(IntPtr instance, int pre_timeout, int post_timeout, int escape_timeout);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetEscSequenceSettings(IntPtr instance, out int pSysGetEscSequenceSettingsRsp);

        #endregion

        #region WIFI Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_SetHostname(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string host_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_GetHostnameBegin(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ppHostName);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityEnterprise5(IntPtr instance, int wlan_handle, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name, [MarshalAs(UnmanagedType.LPStr)] string client_cert_name, [MarshalAs(UnmanagedType.LPStr)] string client_key_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityEnterprise6(IntPtr instance, int wlan_handle, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string ca_name, [MarshalAs(UnmanagedType.LPStr)] string client_cert_name, [MarshalAs(UnmanagedType.LPStr)] string client_key_name, [MarshalAs(UnmanagedType.LPStr)] string identity);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationGetSecurityBegin(IntPtr instance, int wlan_handle, out int pWifiStationGetSecurityRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityPeap4(IntPtr instance, int wlan_handle, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string peap_user, [MarshalAs(UnmanagedType.LPStr)] string peap_password);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityPeap5(IntPtr instance, int wlan_handle, int tls_version, [MarshalAs(UnmanagedType.LPStr)] string peap_user, [MarshalAs(UnmanagedType.LPStr)] string peap_password, [MarshalAs(UnmanagedType.LPStr)] string ca_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityWpa(IntPtr instance, int wlan_handle, [MarshalAs(UnmanagedType.LPStr)] string passphrase, int wpa_threshold);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityOpen(IntPtr instance, int wlan_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetConnectionParams(IntPtr instance, int wlan_handle, [MarshalAs(UnmanagedType.LPStr)] string ssid);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationGetConnectionParamsBegin(IntPtr instance, int wlan_handle, [MarshalAs(UnmanagedType.LPStr)] string ppSsid);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetIpConfigStatic4(IntPtr instance, int wlan_handle, out int ip_addr, out int subnet_mask, out int gateway);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetIpConfigStatic5(IntPtr instance, int wlan_handle, out int ip_addr, out int subnet_mask, out int gateway, out int prim_dns);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetIpConfigStatic6(IntPtr instance, int wlan_handle, out int ip_addr, out int subnet_mask, out int gateway, out int prim_dns, out int sec_dns);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetIpConfigDhcp(IntPtr instance, int wlan_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetIpConfig(IntPtr instance, int wlan_handle, out int pWifiStationGetIpConfigRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationConnect(IntPtr instance, int wlan_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationDisconnect(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetNetworkStatus(IntPtr instance, int net_status_id, out int pNetStatusVal);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_StationListNetworkStatusBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationListNetworkStatusGetNext(IntPtr instance, out int pWifiStationListNetworkStatusRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_SetRegulatoryDomain(IntPtr instance, int reg_domain);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_GetRegulatoryDomain(IntPtr instance, out int pRegDomain);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_SetChannelList(IntPtr instance, IntPtr channel_list, int channel_list_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_GetChannelList(IntPtr instance, out int pChannelList);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_GetActiveChannels(IntPtr instance, out int pChannelList);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_StationScanDefaultBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationScanDefaultGetNext(IntPtr instance, out int pWifiStationScanDefaultRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_StationScan1Begin(IntPtr instance, int scan_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationScan1GetNext(IntPtr instance, out int pWifiStationScanRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_StationScan2Begin(IntPtr instance, int scan_mode, [MarshalAs(UnmanagedType.LPStr)] string ssid);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationScan2GetNext(IntPtr instance, out int pWifiStationScanRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationStatusBegin(IntPtr instance, int status_id, out int pWifiStationStatusRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApActivate(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApDeactivate(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApSetConnectionParams1(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ssid);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApSetConnectionParams2(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string ssid, int channel);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_ApGetConnectionParamsBegin(IntPtr instance, out int pWifiApGetConnectionParamsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApSetSecurityWpa1(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string passphrase);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApSetSecurityWpa2(IntPtr instance, [MarshalAs(UnmanagedType.LPStr)] string passphrase, int wpa_version);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApSetSecurityOpen(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApGetSecurity(IntPtr instance, out int pWifiApGetSecurityRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_ApListStationsBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_ApListStationsGetNext(IntPtr instance, out int pMac);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_ApGetNetworkStatus(IntPtr instance, int net_status_id, out int pNetStatusVal);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_ApListNetworkStatusBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_ApListNetworkStatusGetNext(IntPtr instance, out int pWifiApListNetworkStatusRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_SetWifiRoaming(IntPtr instance, int roaming);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_GetWifiRoaming(IntPtr instance, out int pRoaming);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetRoamingBGScanThreshold(IntPtr instance, int roaming_scanning_threshold);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetRoamingBGScanThreshold(IntPtr instance, out int pRoamingScanningThreshold);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetRoamingSwitchLimit(IntPtr instance, int roaming_switch_limit);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetRoamingSwitchLimit(IntPtr instance, out int pRoamingSwitchLimit);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetRoamingScanInterval(IntPtr instance, int roaming_scan_interval);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetRoamingScanInterval(IntPtr instance, out int pRoamingScanInterval);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetAggressiveRoaming(IntPtr instance, int roaming_aggressive);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetAggressiveRoaming(IntPtr instance, out int pRoamingAggressive);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetRoamingDelayMs(IntPtr instance, int roaming_delay_time);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetRoamingDelayMs(IntPtr instance, out int pRoamingDelayTime);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetRoamingAllChannels(IntPtr instance, int roaming_channels);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationGetRoamingAllChannels(IntPtr instance, out int pRoamingChannels);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterLinkUp(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterLinkDown(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterStationNetworkUp(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterStationNetworkDown(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterStationRoamingSwitchInitiated(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterStationRoamingSwitchFailed(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterStationRoamingSwitchCompleted(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterApNetworkUp(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterApNetworkDown(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterApUp(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterApDown(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterApStationAssociated(IntPtr instance, int callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_wifi_RegisterApStationDisassociated(IntPtr instance, int callback);

        #endregion

    }
}