// Auto-generated UCX API wrapper P/Invoke declarations
// DO NOT EDIT - Generated by generate_wrapper.py

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace UcxAvaloniaApp.Services
{
    public static partial class UcxNativeGenerated
    {
        private const string DllName = "ucxclient_wrapper";

        #region BLUETOOTH Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetMode(IntPtr instance, uBtMode_t mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_GetMode(IntPtr instance, ref uBtMode_t pMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_Connect(IntPtr instance, ref uBtLeAddress_t bd_addr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_Disconnect(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_GetLocalNameBegin(IntPtr instance, ref byte ppDeviceName);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_bluetooth_SetLocalName(IntPtr instance, ref byte device_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_DiscoveryDefaultBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_DiscoveryDefaultGetNext(IntPtr instance, ref uCxBtDiscoveryDefault_t pBtDiscoveryDefaultRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_bluetooth_Discovery1Begin(IntPtr instance, uBtDiscoveryType_t discovery_type);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_bluetooth_Discovery1GetNext(IntPtr instance, ref uCxBtDiscovery_t pBtDiscoveryRsp);

        #endregion

        #region DIAGNOSTICS Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Ping1(IntPtr instance, ref byte destination);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Ping2(IntPtr instance, ref byte destination, int count);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_PingStop(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf2(IntPtr instance, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf5(IntPtr instance, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int port, int report_interval);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf7(IntPtr instance, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int port, int report_interval, int time_boundary, ref uSockIpAddress_t ip_addr);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf8(IntPtr instance, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int port, int report_interval, int time_boundary, ref uSockIpAddress_t ip_addr, int length);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf9(IntPtr instance, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int port, int report_interval, int time_boundary, ref uSockIpAddress_t ip_addr, int length, int bandwidth);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_diagnostics_Iperf10(IntPtr instance, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int port, int report_interval, int time_boundary, ref uSockIpAddress_t ip_addr, int length, int bandwidth, uDiagBidirectional_t bidirectional);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_diagnostics_RegisterPingComplete(IntPtr instance, uUEDGPC_t callback);

        #endregion

        #region GATT_CLIENT Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverPrimaryServicesBegin(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverPrimaryServicesGetNext(IntPtr instance, ref uCxGattClientDiscoverPrimaryServices_t pGattClientDiscoverPrimaryServicesRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverPrimaryServicesByUuidBegin(IntPtr instance, int conn_handle, ref byte uuid, int uuid_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverPrimaryServicesByUuidGetNext(IntPtr instance, ref uCxGattClientDiscoverPrimaryServicesByUuid_t pGattClientDiscoverPrimaryServicesByUuidRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverServiceCharsBegin(IntPtr instance, int conn_handle, int start, int end);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverServiceCharsGetNext(IntPtr instance, ref uCxGattClientDiscoverServiceChars_t pGattClientDiscoverServiceCharsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_gatt_client_DiscoverCharDescriptorsBegin(IntPtr instance, int conn_handle, int value_handle, int char_end_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_DiscoverCharDescriptorsGetNext(IntPtr instance, ref uCxGattClientDiscoverCharDescriptors_t pGattClientDiscoverCharDescriptorsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_ReadBegin(IntPtr instance, int conn_handle, int value_handle, ref uByteArray_t pHexData);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_gatt_client_ReadByUuidBegin(IntPtr instance, int conn_handle, int start, int end, ref byte uuid, int uuid_len, ref uCxGattClientReadByUuid_t pGattClientReadByUuidRsp);

        #endregion

        #region GATT_SERVER Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_ServiceDefine(IntPtr instance, ref byte uuid, int uuid_len, ref int pSerHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_CharDefine5(IntPtr instance, ref byte uuid, int uuid_len, ref byte properties, int properties_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, ref byte value, int value_len, ref uCxGattServerCharDefine_t pGattServerCharDefineRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_CharDefine6(IntPtr instance, ref byte uuid, int uuid_len, ref byte properties, int properties_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, ref byte value, int value_len, int max_length, ref uCxGattServerCharDefine_t pGattServerCharDefineRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_HostCharDefine(IntPtr instance, ref byte uuid, int uuid_len, ref byte properties, int properties_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, ref uCxGattServerHostCharDefine_t pGattServerHostCharDefineRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_DescriptorDefine4(IntPtr instance, ref byte uuid, int uuid_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, ref byte value, int value_len, ref int pDescHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_DescriptorDefine5(IntPtr instance, ref byte uuid, int uuid_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, ref byte value, int value_len, int max_length, ref int pDescHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_ServiceActivate(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_ReadReqResponse(IntPtr instance, int conn_handle, ref byte value, int value_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_SendNotification(IntPtr instance, int conn_handle, int char_handle, ref byte value, int value_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_gatt_server_SendIndication(IntPtr instance, int conn_handle, int char_handle, ref byte value, int value_len);

        #endregion

        #region GENERAL Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_general_Attention(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetManufacturerIdentificationBegin(IntPtr instance, ref byte ppManufacturer);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetDeviceModelIdentificationBegin(IntPtr instance, ref byte ppDeviceModel);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetSoftwareVersionBegin(IntPtr instance, ref byte ppVersion);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetSerialNumberBegin(IntPtr instance, ref byte ppSerialNumber);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetIdentInfoBegin(IntPtr instance, ref uCxGeneralGetIdentInfo_t pGeneralGetIdentInfoRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetTypeCodeBegin(IntPtr instance, ref byte ppTypeCode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_general_SetGreetingText1(IntPtr instance, uGeneralGreetingMode_t greeting_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_general_SetGreetingText2(IntPtr instance, uGeneralGreetingMode_t greeting_mode, ref byte text);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_general_GetGreetingTextBegin(IntPtr instance, ref uCxGeneralGetGreetingText_t pGeneralGetGreetingTextRsp);

        #endregion

        #region HTTP Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetConnectionParams2(IntPtr instance, int session_id, ref byte host);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetConnectionParams3(IntPtr instance, int session_id, ref byte host, int port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetTLS2(IntPtr instance, int session_id, uWifiTlsVersion_t tls_version);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetTLS3(IntPtr instance, int session_id, uWifiTlsVersion_t tls_version, ref byte ca_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_SetTLS5(IntPtr instance, int session_id, uWifiTlsVersion_t tls_version, ref byte ca_name, ref byte client_cert_name, ref byte client_key_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetTLSBegin(IntPtr instance, int session_id, ref uCxHttpGetTLS_t pHttpGetTLSRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_Disconnect(IntPtr instance, int session_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetHeader1Begin(IntPtr instance, int session_id, ref uCxHttpGetHeader_t pHttpGetHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_http_GetHeader2Begin(IntPtr instance, int session_id, int data_length, ref uCxHttpGetHeader_t pHttpGetHeaderRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_http_GetBody(IntPtr instance, int session_id, int data_length, ref byte pDataBuf, ref int pMoreToRead);

        #endregion

        #region MQTT Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams3(IntPtr instance, int mqtt_id, ref byte hostname, int port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams4(IntPtr instance, int mqtt_id, ref byte hostname, int port, ref byte client_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams5(IntPtr instance, int mqtt_id, ref byte hostname, int port, ref byte client_id, ref byte username);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetConnectionParams6(IntPtr instance, int mqtt_id, ref byte hostname, int port, ref byte client_id, ref byte username, ref byte password);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_mqtt_GetConnectionParamsBegin(IntPtr instance, int mqtt_id, ref uCxMqttGetConnectionParams_t pMqttGetConnectionParamsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_Connect(IntPtr instance, int mqtt_id);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetKeepAlive(IntPtr instance, int mqtt_id, int keep_alive);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_GetKeepAlive(IntPtr instance, int mqtt_id, ref int pKeepAlive);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetLastWillAndTestament3(IntPtr instance, int mqtt_id, ref byte topic, ref byte will_msg);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_mqtt_SetLastWillAndTestament4(IntPtr instance, int mqtt_id, ref byte topic, ref byte will_msg, uMqttQos_t qos);

        #endregion

        #region NETWORK_TIME Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_network_time_SetClientEnabled(IntPtr instance, uNtpClientStatus_t client_status);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_network_time_GetClientEnabled(IntPtr instance, ref uNtpClientStatus_t pClientStatus);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_network_time_SetNtpServer(IntPtr instance, int ntp_server_id, ref byte ntp_server_address);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_network_time_GetNtpServerBegin(IntPtr instance, ref uCxNtpGetNtpServer_t pNtpGetNtpServerRsp);

        #endregion

        #region POWER Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_DeepSleepWithGpioWakeup(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_DeepSleep(IntPtr instance, uPowerWakeupMode_t wakeup_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_SetPowerSaveLevel(IntPtr instance, int level);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_GetPowerSaveLevel(IntPtr instance, ref int pLevel);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_power_SetPowerSaveTimeout(IntPtr instance, int timeoutMs);

        #endregion

        #region SECURITY Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateRemove(IntPtr instance, uSecCertType_t cert_type, ref byte name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateRemoveAll(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateUpload(IntPtr instance, uSecCertType_t cert_type, ref byte name, ref byte binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_security_CertificateUploadPW(IntPtr instance, uSecCertType_t cert_type, ref byte name, ref byte password, ref byte binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_security_ListCertificatesBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ListCertificatesGetNext(IntPtr instance, ref uCxSecListCertificates_t pSecListCertificatesRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ReadAllCertificatesDetailsBegin(IntPtr instance, ref byte name, ref uCxSecReadAllCertificatesDetails_t pSecReadAllCertificatesDetailsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ReadCertificatesDetailsBegin(IntPtr instance, ref byte name, uSecCertDetailId_t cert_detail_id, ref uCxSecReadCertificatesDetails_t pSecReadCertificatesDetailsRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_security_ListTlsExtensionsBegin(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_security_ListTlsExtensionsGetNext(IntPtr instance, ref uCxSecListTlsExtensions_t pSecListTlsExtensionsRsp);

        #endregion

        #region SOCKET Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Create1(IntPtr instance, uSocketProtocol_t protocol, ref int pSocketHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Create2(IntPtr instance, uSocketProtocol_t protocol, uSocketPrefIpVer_t pref_ip_ver, ref int pSocketHandle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetTLS2(IntPtr instance, int socket_handle, uWifiTlsVersion_t tls_version);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetTLS3(IntPtr instance, int socket_handle, uWifiTlsVersion_t tls_version, ref byte ca_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetTLS5(IntPtr instance, int socket_handle, uWifiTlsVersion_t tls_version, ref byte ca_name, ref byte client_cert_name, ref byte client_key_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_socket_GetTLSBegin(IntPtr instance, int socket_handle, ref uCxSocketGetTLS_t pSocketGetTLSRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Connect(IntPtr instance, int socket_handle, ref byte host_address, int remote_port);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_SetReadMode(IntPtr instance, uReadMode_t read_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_GetReadMode(IntPtr instance, ref uReadMode_t pReadMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_socket_Write(IntPtr instance, int socket_handle, ref byte binary_data, int binary_data_len);

        #endregion

        #region SPS Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Connect1(IntPtr instance, int conn_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Connect2(IntPtr instance, int conn_handle, int flow_control);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_SetServiceEnable(IntPtr instance, uSpsServiceOption_t service_option);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_GetServiceEnable(IntPtr instance, ref uSpsServiceOption_t pServiceOption);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Write(IntPtr instance, int conn_handle, ref byte binary_data, int binary_data_len);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_SetDataMode(IntPtr instance, uReadMode_t read_mode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_GetDataMode(IntPtr instance, ref uReadMode_t pReadMode);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_sps_Read(IntPtr instance, int conn_handle, int length, ref byte pDataBuf);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_sps_RegisterConnect(IntPtr instance, uUESPSC_t callback);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ucx_sps_RegisterDisconnect(IntPtr instance, uUESPSDC_t callback);

        #endregion

        #region SYSTEM Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_Reboot(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartSerialFirmwareUpdate1(IntPtr instance, int baud_rate);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartSerialFirmwareUpdate2(IntPtr instance, int baud_rate, int flow_control);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartSerialFirmwareUpdateDefault(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartBootLoader1(IntPtr instance, int baud_rate);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartBootLoader2(IntPtr instance, int baud_rate, int flow_control);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StartBootLoaderDefault(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_StoreConfiguration(IntPtr instance);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_GetLocalAddress(IntPtr instance, uInterfaceId_t interface_id, ref uMacAddress_t pAddress);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_system_SetLocalAddress(IntPtr instance, uInterfaceId_t interface_id, ref uMacAddress_t address);

        #endregion

        #region WIFI Functions

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_SetHostname(IntPtr instance, ref byte host_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_GetHostnameBegin(IntPtr instance, ref byte ppHostName);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityEnterprise5(IntPtr instance, int wlan_handle, uWifiTlsVersion_t tls_version, ref byte ca_name, ref byte client_cert_name, ref byte client_key_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityEnterprise6(IntPtr instance, int wlan_handle, uWifiTlsVersion_t tls_version, ref byte ca_name, ref byte client_cert_name, ref byte client_key_name, ref byte identity);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern bool ucx_wifi_StationGetSecurityBegin(IntPtr instance, int wlan_handle, ref uCxWifiStationGetSecurity_t pWifiStationGetSecurityRsp);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityPeap4(IntPtr instance, int wlan_handle, uWifiTlsVersion_t tls_version, ref byte peap_user, ref byte peap_password);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityPeap5(IntPtr instance, int wlan_handle, uWifiTlsVersion_t tls_version, ref byte peap_user, ref byte peap_password, ref byte ca_name);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityWpa(IntPtr instance, int wlan_handle, ref byte passphrase, uWifiWpaThreshold_t wpa_threshold);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetSecurityOpen(IntPtr instance, int wlan_handle);

        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int ucx_wifi_StationSetConnectionParams(IntPtr instance, int wlan_handle, ref byte ssid);

        #endregion

    }
}