/* Auto-generated UCX API wrapper header */
/* DO NOT EDIT - Generated by generate_wrapper.py */
/* NOTE: Include ucxclient_wrapper.h instead of this file directly */

#ifndef UCXCLIENT_WRAPPER_GENERATED_H
#define UCXCLIENT_WRAPPER_GENERATED_H

/* This header is included by ucxclient_wrapper.h which provides all type definitions */
/* Do not include this file directly - it uses opaque forward declarations */

#ifdef __cplusplus
extern "C" {
#endif

/* Function declarations - see ucxclient_wrapper_generated.c */
/* Include ucxclient_wrapper.h to use these functions */

#ifdef __cplusplus
}
#endif

#endif /* UCXCLIENT_WRAPPER_GENERATED_H */