/* Auto-generated UCX API wrapper header */
/* DO NOT EDIT - Generated by generate_wrapper.py */

#ifndef UCXCLIENT_WRAPPER_GENERATED_H
#define UCXCLIENT_WRAPPER_GENERATED_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include UCX API for type definitions */
#include "../ucxclient/ucx_api/u_cx.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declaration */
typedef struct ucx_instance ucx_instance_t;


/* ========== BLUETOOTH FUNCTIONS ========== */
int32_t ucx_bluetooth_SetMode(ucx_instance_t *inst, uBtMode_t mode);
int32_t ucx_bluetooth_GetMode(ucx_instance_t *inst, uBtMode_t * pMode);
int32_t ucx_bluetooth_Connect(ucx_instance_t *inst, uBtLeAddress_t * bd_addr);
int32_t ucx_bluetooth_Disconnect(ucx_instance_t *inst, int32_t conn_handle);
bool ucx_bluetooth_GetLocalNameBegin(ucx_instance_t *inst, const char * * ppDeviceName);
int32_t ucx_bluetooth_SetLocalName(ucx_instance_t *inst, const char * device_name);
void ucx_bluetooth_DiscoveryDefaultBegin(ucx_instance_t *inst);
bool ucx_bluetooth_DiscoveryDefaultGetNext(ucx_instance_t *inst, uCxBtDiscoveryDefault_t * pBtDiscoveryDefaultRsp);
void ucx_bluetooth_Discovery1Begin(ucx_instance_t *inst, uBtDiscoveryType_t discovery_type);
bool ucx_bluetooth_Discovery1GetNext(ucx_instance_t *inst, uCxBtDiscovery_t * pBtDiscoveryRsp);
void ucx_bluetooth_Discovery2Begin(ucx_instance_t *inst, uBtDiscoveryType_t discovery_type, uBtDiscoveryMode_t discovery_mode);
bool ucx_bluetooth_Discovery2GetNext(ucx_instance_t *inst, uCxBtDiscovery_t * pBtDiscoveryRsp);
void ucx_bluetooth_Discovery3Begin(ucx_instance_t *inst, uBtDiscoveryType_t discovery_type, uBtDiscoveryMode_t discovery_mode, int32_t discovery_length);
bool ucx_bluetooth_Discovery3GetNext(ucx_instance_t *inst, uCxBtDiscovery_t * pBtDiscoveryRsp);
int32_t ucx_bluetooth_BgDiscoveryDefaultStart(ucx_instance_t *inst);
int32_t ucx_bluetooth_BgDiscoveryStart1(ucx_instance_t *inst, uBtDiscoveryType_t discovery_type);
int32_t ucx_bluetooth_BgDiscoveryStart2(ucx_instance_t *inst, uBtDiscoveryType_t discovery_type, uBtDiscoveryMode_t discovery_mode);
int32_t ucx_bluetooth_BgDiscoveryStart3(ucx_instance_t *inst, uBtDiscoveryType_t discovery_type, uBtDiscoveryMode_t discovery_mode, uBtOutputEvents_t output_events);
int32_t ucx_bluetooth_BgDiscoveryStop(ucx_instance_t *inst);
int32_t ucx_bluetooth_GetRssi(ucx_instance_t *inst, int32_t conn_handle, int32_t * pRssi);
void ucx_bluetooth_ListConnectionsBegin(ucx_instance_t *inst);
bool ucx_bluetooth_ListConnectionsGetNext(ucx_instance_t *inst, uCxBtListConnections_t * pBtListConnectionsRsp);
void ucx_bluetooth_ListConnectionStatusBegin(ucx_instance_t *inst, int32_t conn_handle);
bool ucx_bluetooth_ListConnectionStatusGetNext(ucx_instance_t *inst, uCxBtListConnectionStatus_t * pBtListConnectionStatusRsp);
int32_t ucx_bluetooth_GetConnectionStatus(ucx_instance_t *inst, int32_t conn_handle, uBtPropId_t prop_id, int32_t * pStatusVal);
int32_t ucx_bluetooth_GetAdvertiseInformation(ucx_instance_t *inst, uCxBtGetAdvertiseInformation_t * pBtGetAdvertiseInformationRsp);
int32_t ucx_bluetooth_SetLegacyAdvertiseData(ucx_instance_t *inst, const uint8_t * adv_data, int32_t adv_data_len);
bool ucx_bluetooth_GetLegacyAdvertiseDataBegin(ucx_instance_t *inst, uByteArray_t * pAdvData);
int32_t ucx_bluetooth_ClearLegacyAdvertiseData(ucx_instance_t *inst);
int32_t ucx_bluetooth_SetScanResponseData(ucx_instance_t *inst, const uint8_t * scan_rsp_data, int32_t scan_rsp_data_len);
bool ucx_bluetooth_GetScanResponseDataBegin(ucx_instance_t *inst, uByteArray_t * pScanRspData);
int32_t ucx_bluetooth_ClearScanResponseData(ucx_instance_t *inst);
int32_t ucx_bluetooth_LegacyAdvertisementStart(ucx_instance_t *inst);
int32_t ucx_bluetooth_LegacyAdvertisementStop(ucx_instance_t *inst);
int32_t ucx_bluetooth_DirectedAdvertisementStart1(ucx_instance_t *inst, uBtLeAddress_t * bd_addr);
int32_t ucx_bluetooth_DirectedAdvertisementStart2(ucx_instance_t *inst, uBtLeAddress_t * bd_addr, int32_t timeout);
int32_t ucx_bluetooth_DirectedAdvertisementStop(ucx_instance_t *inst);
int32_t ucx_bluetooth_SetConnectionIntervalMin(ucx_instance_t *inst, int32_t connection_interval_minimum);
int32_t ucx_bluetooth_GetConnectionIntervalMin(ucx_instance_t *inst, int32_t * pConnectionIntervalMinimum);
int32_t ucx_bluetooth_SetConnectionIntervalMax(ucx_instance_t *inst, int32_t connection_interval_maximum);
int32_t ucx_bluetooth_GetConnectionIntervalMax(ucx_instance_t *inst, int32_t * pConnectionIntervalMaximum);
int32_t ucx_bluetooth_SetConnectionPeripheralLatency(ucx_instance_t *inst, int32_t connection_peripheral_latency);
int32_t ucx_bluetooth_GetConnectionPeripheralLatency(ucx_instance_t *inst, int32_t * pConnectionPeripheralLatency);
int32_t ucx_bluetooth_SetConnectionLinklossTimeout(ucx_instance_t *inst, int32_t connection_linkloss_timeout);
int32_t ucx_bluetooth_GetConnectionLinklossTimeout(ucx_instance_t *inst, int32_t * pConnectionLinklossTimeout);
int32_t ucx_bluetooth_SetPreferredTxPhy(ucx_instance_t *inst, int32_t preferred_tx_phy);
int32_t ucx_bluetooth_GetPreferredTxPhy(ucx_instance_t *inst, int32_t * pPreferredTxPhy);
int32_t ucx_bluetooth_SetPreferredRxPhy(ucx_instance_t *inst, int32_t preferred_rx_phy);
int32_t ucx_bluetooth_GetPreferredRxPhy(ucx_instance_t *inst, int32_t * pPreferredRxPhy);
int32_t ucx_bluetooth_SetLegacyAdvertisementConfig(ucx_instance_t *inst, int32_t advertisement_interval_minimum, int32_t advertisement_interval_maximum);
int32_t ucx_bluetooth_GetLegacyAdvertisementConfig(ucx_instance_t *inst, uCxBtGetLegacyAdvertisementConfig_t * pBtGetLegacyAdvertisementConfigRsp);
int32_t ucx_bluetooth_SetScanInterval(ucx_instance_t *inst, int32_t scan_interval);
int32_t ucx_bluetooth_GetScanInterval(ucx_instance_t *inst, int32_t * pScanInterval);
int32_t ucx_bluetooth_SetScanWindow(ucx_instance_t *inst, int32_t scan_window);
int32_t ucx_bluetooth_GetScanWindow(ucx_instance_t *inst, int32_t * pScanWindow);
int32_t ucx_bluetooth_SetConnectToDirectedAdv(ucx_instance_t *inst, int32_t connect_to_directed_adv);
int32_t ucx_bluetooth_GetConnectToDirectedAdv(ucx_instance_t *inst, int32_t * pConnectToDirectedAdv);
int32_t ucx_bluetooth_SetIoCapabilities(ucx_instance_t *inst, uBtIoCap_t io_cap);
int32_t ucx_bluetooth_GetIoCapabilities(ucx_instance_t *inst, uBtIoCap_t * pIoCap);
int32_t ucx_bluetooth_SetSecurityMode(ucx_instance_t *inst, uBtSecurityMode_t security_mode);
int32_t ucx_bluetooth_GetSecurityMode(ucx_instance_t *inst, uBtSecurityMode_t * pSecurityMode);
int32_t ucx_bluetooth_SetPairingMode(ucx_instance_t *inst, uBtPairingMode_t pairing_mode);
int32_t ucx_bluetooth_GetPairingMode(ucx_instance_t *inst, uBtPairingMode_t * pPairingMode);
int32_t ucx_bluetooth_UserConfirmation(ucx_instance_t *inst, uBtLeAddress_t * bd_addr, uBtConfirm_t confirm);
int32_t ucx_bluetooth_UserPasskeyEntry2(ucx_instance_t *inst, uBtLeAddress_t * bd_addr, uBtConfirm_t confirm);
int32_t ucx_bluetooth_UserPasskeyEntry3(ucx_instance_t *inst, uBtLeAddress_t * bd_addr, uBtConfirm_t confirm, int32_t passkey);
int32_t ucx_bluetooth_Bond(ucx_instance_t *inst, uBtLeAddress_t * bd_addr);
int32_t ucx_bluetooth_Unbond(ucx_instance_t *inst, uBtLeAddress_t * bd_addr);
int32_t ucx_bluetooth_UnbondAll(ucx_instance_t *inst);
void ucx_bluetooth_ListBondedDevicesBegin(ucx_instance_t *inst);
bool ucx_bluetooth_ListBondedDevicesGetNext(ucx_instance_t *inst, uBtLeAddress_t * pBdAddr);
int32_t ucx_bluetooth_SetDeviceInfoServiceChar(ucx_instance_t *inst, uBtCharId_t char_id, const char * char_value);
bool ucx_bluetooth_GetDeviceInfoServiceCharBegin(ucx_instance_t *inst, uBtCharId_t char_id, const char * * ppCharValue);
void ucx_bluetooth_ListDeviceInfoServiceCharsBegin(ucx_instance_t *inst);
bool ucx_bluetooth_ListDeviceInfoServiceCharsGetNext(ucx_instance_t *inst, uCxBtListDeviceInfoServiceChars_t * pBtListDeviceInfoServiceCharsRsp);
int32_t ucx_bluetooth_RequestPhy(ucx_instance_t *inst, int32_t conn_handle, int32_t tx_phy, int32_t rx_phy);
int32_t ucx_bluetooth_GetPhy(ucx_instance_t *inst, int32_t conn_handle, uCxBtGetPhy_t * pBtGetPhyRsp);
void ucx_bluetooth_RegisterConnect(ucx_instance_t *inst, uUEBTC_t callback);
void ucx_bluetooth_RegisterDisconnect(ucx_instance_t *inst, uUEBTDC_t callback);
void ucx_bluetooth_RegisterBondStatus(ucx_instance_t *inst, uUEBTB_t callback);
void ucx_bluetooth_RegisterUserConfirmation(ucx_instance_t *inst, uUEBTUC_t callback);
void ucx_bluetooth_RegisterPasskeyEntry(ucx_instance_t *inst, uUEBTUPD_t callback);
void ucx_bluetooth_RegisterPasskeyRequest(ucx_instance_t *inst, uUEBTUPE_t callback);
void ucx_bluetooth_RegisterPhyUpdate(ucx_instance_t *inst, uUEBTPHYU_t callback);
void ucx_bluetooth_RegisterBackgroundDiscovery(ucx_instance_t *inst, uUEBTBGD_t callback);

/* ========== DIAGNOSTICS FUNCTIONS ========== */
int32_t ucx_diagnostics_Ping1(ucx_instance_t *inst, const char * destination);
int32_t ucx_diagnostics_Ping2(ucx_instance_t *inst, const char * destination, int32_t count);
int32_t ucx_diagnostics_PingStop(ucx_instance_t *inst);
int32_t ucx_diagnostics_Iperf2(ucx_instance_t *inst, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type);
int32_t ucx_diagnostics_Iperf5(ucx_instance_t *inst, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int32_t port, int32_t report_interval);
int32_t ucx_diagnostics_Iperf7(ucx_instance_t *inst, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int32_t port, int32_t report_interval, int32_t time_boundary, uSockIpAddress_t * ip_addr);
int32_t ucx_diagnostics_Iperf8(ucx_instance_t *inst, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int32_t port, int32_t report_interval, int32_t time_boundary, uSockIpAddress_t * ip_addr, int32_t length);
int32_t ucx_diagnostics_Iperf9(ucx_instance_t *inst, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int32_t port, int32_t report_interval, int32_t time_boundary, uSockIpAddress_t * ip_addr, int32_t length, int32_t bandwidth);
int32_t ucx_diagnostics_Iperf10(ucx_instance_t *inst, uDiagIperfAction_t iperf_action, uDiagProtocolType_t protocol_type, uDiagRole_t role, int32_t port, int32_t report_interval, int32_t time_boundary, uSockIpAddress_t * ip_addr, int32_t length, int32_t bandwidth, uDiagBidirectional_t bidirectional);
void ucx_diagnostics_RegisterPingComplete(ucx_instance_t *inst, uUEDGPC_t callback);
void ucx_diagnostics_RegisterPingResponse(ucx_instance_t *inst, uUEDGP_t callback);
void ucx_diagnostics_RegisterIperfOutput(ucx_instance_t *inst, uUEDGI_t callback);

/* ========== GATT_CLIENT FUNCTIONS ========== */
void ucx_gatt_client_DiscoverPrimaryServicesBegin(ucx_instance_t *inst, int32_t conn_handle);
bool ucx_gatt_client_DiscoverPrimaryServicesGetNext(ucx_instance_t *inst, uCxGattClientDiscoverPrimaryServices_t * pGattClientDiscoverPrimaryServicesRsp);
void ucx_gatt_client_DiscoverPrimaryServicesByUuidBegin(ucx_instance_t *inst, int32_t conn_handle, const uint8_t * uuid, int32_t uuid_len);
bool ucx_gatt_client_DiscoverPrimaryServicesByUuidGetNext(ucx_instance_t *inst, uCxGattClientDiscoverPrimaryServicesByUuid_t * pGattClientDiscoverPrimaryServicesByUuidRsp);
void ucx_gatt_client_DiscoverServiceCharsBegin(ucx_instance_t *inst, int32_t conn_handle, int32_t start, int32_t end);
bool ucx_gatt_client_DiscoverServiceCharsGetNext(ucx_instance_t *inst, uCxGattClientDiscoverServiceChars_t * pGattClientDiscoverServiceCharsRsp);
void ucx_gatt_client_DiscoverCharDescriptorsBegin(ucx_instance_t *inst, int32_t conn_handle, int32_t value_handle, int32_t char_end_handle);
bool ucx_gatt_client_DiscoverCharDescriptorsGetNext(ucx_instance_t *inst, uCxGattClientDiscoverCharDescriptors_t * pGattClientDiscoverCharDescriptorsRsp);
bool ucx_gatt_client_ReadBegin(ucx_instance_t *inst, int32_t conn_handle, int32_t value_handle, uByteArray_t * pHexData);
bool ucx_gatt_client_ReadByUuidBegin(ucx_instance_t *inst, int32_t conn_handle, int32_t start, int32_t end, const uint8_t * uuid, int32_t uuid_len, uCxGattClientReadByUuid_t * pGattClientReadByUuidRsp);
int32_t ucx_gatt_client_Write(ucx_instance_t *inst, int32_t conn_handle, int32_t value_handle, const uint8_t * hex_data, int32_t hex_data_len);
int32_t ucx_gatt_client_ConfigWrite(ucx_instance_t *inst, int32_t conn_handle, int32_t desc_handle, uGattClientConfig_t config);
int32_t ucx_gatt_client_WriteNoRsp(ucx_instance_t *inst, int32_t conn_handle, int32_t value_handle, const uint8_t * hex_data, int32_t hex_data_len);
int32_t ucx_gatt_client_WriteLong(ucx_instance_t *inst, int32_t conn_handle, int32_t value_handle, const uint8_t * hex_data, int32_t hex_data_len, uGattClientReliable_t reliable, uGattClientFlag_t flag, int32_t offset);
void ucx_gatt_client_RegisterNotification(ucx_instance_t *inst, uUEBTGCN_t callback);
void ucx_gatt_client_RegisterIndication(ucx_instance_t *inst, uUEBTGCI_t callback);

/* ========== GATT_SERVER FUNCTIONS ========== */
int32_t ucx_gatt_server_ServiceDefine(ucx_instance_t *inst, const uint8_t * uuid, int32_t uuid_len, int32_t * pSerHandle);
int32_t ucx_gatt_server_CharDefine5(ucx_instance_t *inst, const uint8_t * uuid, int32_t uuid_len, const uint8_t * properties, int32_t properties_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, const uint8_t * value, int32_t value_len, uCxGattServerCharDefine_t * pGattServerCharDefineRsp);
int32_t ucx_gatt_server_CharDefine6(ucx_instance_t *inst, const uint8_t * uuid, int32_t uuid_len, const uint8_t * properties, int32_t properties_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, const uint8_t * value, int32_t value_len, int32_t max_length, uCxGattServerCharDefine_t * pGattServerCharDefineRsp);
int32_t ucx_gatt_server_HostCharDefine(ucx_instance_t *inst, const uint8_t * uuid, int32_t uuid_len, const uint8_t * properties, int32_t properties_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, uCxGattServerHostCharDefine_t * pGattServerHostCharDefineRsp);
int32_t ucx_gatt_server_DescriptorDefine4(ucx_instance_t *inst, const uint8_t * uuid, int32_t uuid_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, const uint8_t * value, int32_t value_len, int32_t * pDescHandle);
int32_t ucx_gatt_server_DescriptorDefine5(ucx_instance_t *inst, const uint8_t * uuid, int32_t uuid_len, uGattServerReadSecurity_t read_security, uGattServerWriteSecurity_t write_security, const uint8_t * value, int32_t value_len, int32_t max_length, int32_t * pDescHandle);
int32_t ucx_gatt_server_ServiceActivate(ucx_instance_t *inst);
int32_t ucx_gatt_server_ReadReqResponse(ucx_instance_t *inst, int32_t conn_handle, const uint8_t * value, int32_t value_len);
int32_t ucx_gatt_server_SendNotification(ucx_instance_t *inst, int32_t conn_handle, int32_t char_handle, const uint8_t * value, int32_t value_len);
int32_t ucx_gatt_server_SendIndication(ucx_instance_t *inst, int32_t conn_handle, int32_t char_handle, const uint8_t * value, int32_t value_len);
int32_t ucx_gatt_server_SetAttrValue(ucx_instance_t *inst, int32_t attr_handle, const uint8_t * value, int32_t value_len);
int32_t ucx_gatt_server_ReadReqError(ucx_instance_t *inst, int32_t conn_handle, const uint8_t * error_code, int32_t error_code_len);
int32_t ucx_gatt_server_WriteReqError(ucx_instance_t *inst, int32_t conn_handle, const uint8_t * error_code, int32_t error_code_len);
int32_t ucx_gatt_server_WriteReqResponse(ucx_instance_t *inst, int32_t conn_handle);
int32_t ucx_gatt_server_SendServiceChangedInd(ucx_instance_t *inst, int32_t conn_handle, int32_t start_handle, int32_t end_handle);
void ucx_gatt_server_RegisterNotification(ucx_instance_t *inst, uUEBTGCW_t callback);
void ucx_gatt_server_RegisterReadAttribute(ucx_instance_t *inst, uUEBTGRR_t callback);
void ucx_gatt_server_RegisterIndicationAck(ucx_instance_t *inst, uUEBTGIC_t callback);

/* ========== GENERAL FUNCTIONS ========== */
int32_t ucx_general_Attention(ucx_instance_t *inst);
bool ucx_general_GetManufacturerIdentificationBegin(ucx_instance_t *inst, const char * * ppManufacturer);
bool ucx_general_GetDeviceModelIdentificationBegin(ucx_instance_t *inst, const char * * ppDeviceModel);
bool ucx_general_GetSoftwareVersionBegin(ucx_instance_t *inst, const char * * ppVersion);
bool ucx_general_GetSerialNumberBegin(ucx_instance_t *inst, const char * * ppSerialNumber);
bool ucx_general_GetIdentInfoBegin(ucx_instance_t *inst, uCxGeneralGetIdentInfo_t * pGeneralGetIdentInfoRsp);
bool ucx_general_GetTypeCodeBegin(ucx_instance_t *inst, const char * * ppTypeCode);
int32_t ucx_general_SetGreetingText1(ucx_instance_t *inst, uGeneralGreetingMode_t greeting_mode);
int32_t ucx_general_SetGreetingText2(ucx_instance_t *inst, uGeneralGreetingMode_t greeting_mode, const char * text);
bool ucx_general_GetGreetingTextBegin(ucx_instance_t *inst, uCxGeneralGetGreetingText_t * pGeneralGetGreetingTextRsp);
void ucx_general_RegisterStartup(ucx_instance_t *inst, uSTARTUP_t callback);

/* ========== HTTP FUNCTIONS ========== */
int32_t ucx_http_SetConnectionParams2(ucx_instance_t *inst, int32_t session_id, const char * host);
int32_t ucx_http_SetConnectionParams3(ucx_instance_t *inst, int32_t session_id, const char * host, int32_t port);
int32_t ucx_http_SetTLS2(ucx_instance_t *inst, int32_t session_id, uWifiTlsVersion_t tls_version);
int32_t ucx_http_SetTLS3(ucx_instance_t *inst, int32_t session_id, uWifiTlsVersion_t tls_version, const char * ca_name);
int32_t ucx_http_SetTLS5(ucx_instance_t *inst, int32_t session_id, uWifiTlsVersion_t tls_version, const char * ca_name, const char * client_cert_name, const char * client_key_name);
bool ucx_http_GetTLSBegin(ucx_instance_t *inst, int32_t session_id, uCxHttpGetTLS_t * pHttpGetTLSRsp);
int32_t ucx_http_Disconnect(ucx_instance_t *inst, int32_t session_id);
bool ucx_http_GetHeader1Begin(ucx_instance_t *inst, int32_t session_id, uCxHttpGetHeader_t * pHttpGetHeaderRsp);
bool ucx_http_GetHeader2Begin(ucx_instance_t *inst, int32_t session_id, int32_t data_length, uCxHttpGetHeader_t * pHttpGetHeaderRsp);
int32_t ucx_http_GetBody(ucx_instance_t *inst, int32_t session_id, int32_t data_length, uint8_t * pDataBuf, int32_t * pMoreToRead);
int32_t ucx_http_AddHeaderField(ucx_instance_t *inst, int32_t session_id, const char * field_name, const char * field_value);
int32_t ucx_http_SetCustomHeader(ucx_instance_t *inst, int32_t session_id, const char * header_data);
int32_t ucx_http_ClearHeaderCustom(ucx_instance_t *inst, int32_t session_id);
int32_t ucx_http_SetRequestPath(ucx_instance_t *inst, int32_t session_id, const char * path);
bool ucx_http_GetRequestPathBegin(ucx_instance_t *inst, int32_t session_id, uCxHttpGetRequestPath_t * pHttpGetRequestPathRsp);
int32_t ucx_http_GetRequest(ucx_instance_t *inst, int32_t session_id);
bool ucx_http_GetGetRequestHeaderBegin(ucx_instance_t *inst, int32_t session_id, uCxHttpGetGetRequestHeader_t * pHttpGetGetRequestHeaderRsp);
int32_t ucx_http_DeleteRequest1(ucx_instance_t *inst, int32_t session_id);
int32_t ucx_http_DeleteRequest2(ucx_instance_t *inst, int32_t session_id, const char * byte_array_data, int32_t byte_array_data_len);
bool ucx_http_GetDeleteRequestHeaderBegin(ucx_instance_t *inst, int32_t session_id, uCxHttpGetDeleteRequestHeader_t * pHttpGetDeleteRequestHeaderRsp);
int32_t ucx_http_PostRequest(ucx_instance_t *inst, int32_t session_id, const uint8_t * binary_data, int32_t binary_data_len);
bool ucx_http_GetPostRequestHeaderBegin(ucx_instance_t *inst, int32_t session_id, uCxHttpGetPostRequestHeader_t * pHttpGetPostRequestHeaderRsp);
int32_t ucx_http_PutRequest(ucx_instance_t *inst, int32_t session_id, const uint8_t * binary_data, int32_t binary_data_len);
bool ucx_http_GetPutRequestHeaderBegin(ucx_instance_t *inst, int32_t session_id, uCxHttpGetPutRequestHeader_t * pHttpGetPutRequestHeaderRsp);
void ucx_http_RegisterDisconnect(ucx_instance_t *inst, uUEHTCDC_t callback);
void ucx_http_RegisterRequestStatus(ucx_instance_t *inst, uUEHTCRS_t callback);

/* ========== MQTT FUNCTIONS ========== */
int32_t ucx_mqtt_SetConnectionParams3(ucx_instance_t *inst, int32_t mqtt_id, const char * hostname, int32_t port);
int32_t ucx_mqtt_SetConnectionParams4(ucx_instance_t *inst, int32_t mqtt_id, const char * hostname, int32_t port, const char * client_id);
int32_t ucx_mqtt_SetConnectionParams5(ucx_instance_t *inst, int32_t mqtt_id, const char * hostname, int32_t port, const char * client_id, const char * username);
int32_t ucx_mqtt_SetConnectionParams6(ucx_instance_t *inst, int32_t mqtt_id, const char * hostname, int32_t port, const char * client_id, const char * username, const char * password);
bool ucx_mqtt_GetConnectionParamsBegin(ucx_instance_t *inst, int32_t mqtt_id, uCxMqttGetConnectionParams_t * pMqttGetConnectionParamsRsp);
int32_t ucx_mqtt_Connect(ucx_instance_t *inst, int32_t mqtt_id);
int32_t ucx_mqtt_SetKeepAlive(ucx_instance_t *inst, int32_t mqtt_id, int32_t keep_alive);
int32_t ucx_mqtt_GetKeepAlive(ucx_instance_t *inst, int32_t mqtt_id, int32_t * pKeepAlive);
int32_t ucx_mqtt_SetLastWillAndTestament3(ucx_instance_t *inst, int32_t mqtt_id, const char * topic, const char * will_msg);
int32_t ucx_mqtt_SetLastWillAndTestament4(ucx_instance_t *inst, int32_t mqtt_id, const char * topic, const char * will_msg, uMqttQos_t qos);
int32_t ucx_mqtt_SetLastWillAndTestament5(ucx_instance_t *inst, int32_t mqtt_id, const char * topic, const char * will_msg, uMqttQos_t qos, uMqttRetain_t retain);
bool ucx_mqtt_GetLastWillAndTestamentBegin(ucx_instance_t *inst, int32_t mqtt_id, uCxMqttGetLastWillAndTestament_t * pMqttGetLastWillAndTestamentRsp);
int32_t ucx_mqtt_SetTLS2(ucx_instance_t *inst, int32_t mqtt_id, uWifiTlsVersion_t tls_version);
int32_t ucx_mqtt_SetTLS3(ucx_instance_t *inst, int32_t mqtt_id, uWifiTlsVersion_t tls_version, const char * ca_name);
int32_t ucx_mqtt_SetTLS5(ucx_instance_t *inst, int32_t mqtt_id, uWifiTlsVersion_t tls_version, const char * ca_name, const char * client_cert_name, const char * client_key_name);
bool ucx_mqtt_GetTLSBegin(ucx_instance_t *inst, int32_t mqtt_id, uCxMqttGetTLS_t * pMqttGetTLSRsp);
int32_t ucx_mqtt_Disconnect(ucx_instance_t *inst, int32_t mqtt_id);
int32_t ucx_mqtt_Publish(ucx_instance_t *inst, int32_t mqtt_id, uMqttQos_t qos, uMqttRetain_t retain, const char * topic, const uint8_t * binary_data, int32_t binary_data_len);
int32_t ucx_mqtt_Subscribe3(ucx_instance_t *inst, int32_t mqtt_id, uMqttSubscribeAction_t subscribe_action, const char * topic);
int32_t ucx_mqtt_Subscribe4(ucx_instance_t *inst, int32_t mqtt_id, uMqttSubscribeAction_t subscribe_action, const char * topic, uMqttQos_t qos);
int32_t ucx_mqtt_ReadBegin(ucx_instance_t *inst, int32_t mqtt_id, uint8_t * pDataBuf, uint16_t dataBufLength, const char * * ppTopic);
void ucx_mqtt_RegisterConnect(ucx_instance_t *inst, uUEMQC_t callback);
void ucx_mqtt_RegisterDisconnect(ucx_instance_t *inst, uUEMQDC_t callback);
void ucx_mqtt_RegisterDataAvailable(ucx_instance_t *inst, uUEMQDA_t callback);
void ucx_mqtt_RegisterDataDropped(ucx_instance_t *inst, uUEMQDD_t callback);
void ucx_mqtt_RegisterPublishCompleted(ucx_instance_t *inst, uUEMQPC_t callback);
void ucx_mqtt_RegisterSubscribeCompleted(ucx_instance_t *inst, uUEMQSC_t callback);

/* ========== NETWORK_TIME FUNCTIONS ========== */
int32_t ucx_network_time_SetClientEnabled(ucx_instance_t *inst, uNtpClientStatus_t client_status);
int32_t ucx_network_time_GetClientEnabled(ucx_instance_t *inst, uNtpClientStatus_t * pClientStatus);
int32_t ucx_network_time_SetNtpServer(ucx_instance_t *inst, int32_t ntp_server_id, const char * ntp_server_address);
bool ucx_network_time_GetNtpServerBegin(ucx_instance_t *inst, uCxNtpGetNtpServer_t * pNtpGetNtpServerRsp);

/* ========== POWER FUNCTIONS ========== */
int32_t ucx_power_DeepSleepWithGpioWakeup(ucx_instance_t *inst);
int32_t ucx_power_DeepSleep(ucx_instance_t *inst, uPowerWakeupMode_t wakeup_mode);
int32_t ucx_power_SetPowerSaveLevel(ucx_instance_t *inst, int32_t level);
int32_t ucx_power_GetPowerSaveLevel(ucx_instance_t *inst, int32_t * pLevel);
int32_t ucx_power_SetPowerSaveTimeout(ucx_instance_t *inst, int32_t timeoutMs);

/* ========== SECURITY FUNCTIONS ========== */
int32_t ucx_security_CertificateRemove(ucx_instance_t *inst, uSecCertType_t cert_type, const char * name);
int32_t ucx_security_CertificateRemoveAll(ucx_instance_t *inst);
int32_t ucx_security_CertificateUpload(ucx_instance_t *inst, uSecCertType_t cert_type, const char * name, const uint8_t * binary_data, int32_t binary_data_len);
int32_t ucx_security_CertificateUploadPW(ucx_instance_t *inst, uSecCertType_t cert_type, const char * name, const char * password, const uint8_t * binary_data, int32_t binary_data_len);
void ucx_security_ListCertificatesBegin(ucx_instance_t *inst);
bool ucx_security_ListCertificatesGetNext(ucx_instance_t *inst, uCxSecListCertificates_t * pSecListCertificatesRsp);
bool ucx_security_ReadAllCertificatesDetailsBegin(ucx_instance_t *inst, const char * name, uCxSecReadAllCertificatesDetails_t * pSecReadAllCertificatesDetailsRsp);
bool ucx_security_ReadCertificatesDetailsBegin(ucx_instance_t *inst, const char * name, uSecCertDetailId_t cert_detail_id, uCxSecReadCertificatesDetails_t * pSecReadCertificatesDetailsRsp);
void ucx_security_ListTlsExtensionsBegin(ucx_instance_t *inst);
bool ucx_security_ListTlsExtensionsGetNext(ucx_instance_t *inst, uCxSecListTlsExtensions_t * pSecListTlsExtensionsRsp);
int32_t ucx_security_SetTlsServerNameIndication(ucx_instance_t *inst, uEnabled_t enabled);
int32_t ucx_security_GetTlsServerNameIndication(ucx_instance_t *inst, uEnabled_t * pEnabled);
int32_t ucx_security_SetTlsHandshakeFrag(ucx_instance_t *inst, uEnabled_t enabled);
int32_t ucx_security_GetTlsHandshakeFrag(ucx_instance_t *inst, uEnabled_t * pEnabled);

/* ========== SOCKET FUNCTIONS ========== */
int32_t ucx_socket_Create1(ucx_instance_t *inst, uSocketProtocol_t protocol, int32_t * pSocketHandle);
int32_t ucx_socket_Create2(ucx_instance_t *inst, uSocketProtocol_t protocol, uSocketPrefIpVer_t pref_ip_ver, int32_t * pSocketHandle);
int32_t ucx_socket_SetTLS2(ucx_instance_t *inst, int32_t socket_handle, uWifiTlsVersion_t tls_version);
int32_t ucx_socket_SetTLS3(ucx_instance_t *inst, int32_t socket_handle, uWifiTlsVersion_t tls_version, const char * ca_name);
int32_t ucx_socket_SetTLS5(ucx_instance_t *inst, int32_t socket_handle, uWifiTlsVersion_t tls_version, const char * ca_name, const char * client_cert_name, const char * client_key_name);
bool ucx_socket_GetTLSBegin(ucx_instance_t *inst, int32_t socket_handle, uCxSocketGetTLS_t * pSocketGetTLSRsp);
int32_t ucx_socket_Connect(ucx_instance_t *inst, int32_t socket_handle, const char * host_address, int32_t remote_port);
int32_t ucx_socket_SetReadMode(ucx_instance_t *inst, uReadMode_t read_mode);
int32_t ucx_socket_GetReadMode(ucx_instance_t *inst, uReadMode_t * pReadMode);
int32_t ucx_socket_Write(ucx_instance_t *inst, int32_t socket_handle, const uint8_t * binary_data, int32_t binary_data_len);
int32_t ucx_socket_Close(ucx_instance_t *inst, int32_t socket_handle);
int32_t ucx_socket_Read(ucx_instance_t *inst, int32_t socket_handle, int32_t length, uint8_t * pDataBuf);
int32_t ucx_socket_GetLastError(ucx_instance_t *inst, int32_t * pErrorCode);
int32_t ucx_socket_Bind(ucx_instance_t *inst, int32_t socket_handle, int32_t local_port);
int32_t ucx_socket_Listen1(ucx_instance_t *inst, int32_t socket_handle);
int32_t ucx_socket_Listen2(ucx_instance_t *inst, int32_t socket_handle, int32_t port);
int32_t ucx_socket_ReceiveFrom(ucx_instance_t *inst, int32_t socket_handle, int32_t length, uint8_t * pDataBuf, uCxSocketReceiveFrom_t * pSocketReceiveFromRsp);
int32_t ucx_socket_GetPeerAddress(ucx_instance_t *inst, int32_t socket_handle, uCxSocketGetPeerAddress_t * pSocketGetPeerAddressRsp);
void ucx_socket_ListStatusBegin(ucx_instance_t *inst);
bool ucx_socket_ListStatusGetNext(ucx_instance_t *inst, uCxSocketListStatus_t * pSocketListStatusRsp);
int32_t ucx_socket_GetStatus(ucx_instance_t *inst, int32_t socket_handle, uCxSocketGetStatus_t * pSocketGetStatusRsp);
int32_t ucx_socket_SetOption(ucx_instance_t *inst, int32_t socket_handle, uSocketOption_t option, int32_t value);
int32_t ucx_socket_GetOption(ucx_instance_t *inst, int32_t socket_handle, uSocketOption_t option, int32_t * pValue);
int32_t ucx_socket_GetHostByName(ucx_instance_t *inst, const char * host_name, uSockIpAddress_t * pHostIp);
void ucx_socket_RegisterConnect(ucx_instance_t *inst, uUESOC_t callback);
void ucx_socket_RegisterDataAvailable(ucx_instance_t *inst, uUESODA_t callback);
void ucx_socket_RegisterClosed(ucx_instance_t *inst, uUESOCL_t callback);
void ucx_socket_RegisterIncomingConnection(ucx_instance_t *inst, uUESOIC_t callback);

/* ========== SPS FUNCTIONS ========== */
int32_t ucx_sps_Connect1(ucx_instance_t *inst, int32_t conn_handle);
int32_t ucx_sps_Connect2(ucx_instance_t *inst, int32_t conn_handle, int32_t flow_control);
int32_t ucx_sps_SetServiceEnable(ucx_instance_t *inst, uSpsServiceOption_t service_option);
int32_t ucx_sps_GetServiceEnable(ucx_instance_t *inst, uSpsServiceOption_t * pServiceOption);
int32_t ucx_sps_Write(ucx_instance_t *inst, int32_t conn_handle, const uint8_t * binary_data, int32_t binary_data_len);
int32_t ucx_sps_SetDataMode(ucx_instance_t *inst, uReadMode_t read_mode);
int32_t ucx_sps_GetDataMode(ucx_instance_t *inst, uReadMode_t * pReadMode);
int32_t ucx_sps_Read(ucx_instance_t *inst, int32_t conn_handle, int32_t length, uint8_t * pDataBuf);
void ucx_sps_RegisterConnect(ucx_instance_t *inst, uUESPSC_t callback);
void ucx_sps_RegisterDisconnect(ucx_instance_t *inst, uUESPSDC_t callback);
void ucx_sps_RegisterDataAvailable(ucx_instance_t *inst, uUESPSDA_t callback);

/* ========== SYSTEM FUNCTIONS ========== */
int32_t ucx_system_Reboot(ucx_instance_t *inst);
int32_t ucx_system_StartSerialFirmwareUpdate1(ucx_instance_t *inst, int32_t baud_rate);
int32_t ucx_system_StartSerialFirmwareUpdate2(ucx_instance_t *inst, int32_t baud_rate, int32_t flow_control);
int32_t ucx_system_StartSerialFirmwareUpdateDefault(ucx_instance_t *inst);
int32_t ucx_system_StartBootLoader1(ucx_instance_t *inst, int32_t baud_rate);
int32_t ucx_system_StartBootLoader2(ucx_instance_t *inst, int32_t baud_rate, int32_t flow_control);
int32_t ucx_system_StartBootLoaderDefault(ucx_instance_t *inst);
int32_t ucx_system_StoreConfiguration(ucx_instance_t *inst);
int32_t ucx_system_GetLocalAddress(ucx_instance_t *inst, uInterfaceId_t interface_id, uMacAddress_t * pAddress);
int32_t ucx_system_SetLocalAddress(ucx_instance_t *inst, uInterfaceId_t interface_id, uMacAddress_t * address);
int32_t ucx_system_FactoryReset(ucx_instance_t *inst);
int32_t ucx_system_DefaultSettings(ucx_instance_t *inst);
int32_t ucx_system_SetUartSettings1(ucx_instance_t *inst, int32_t baud_rate);
int32_t ucx_system_SetUartSettings2(ucx_instance_t *inst, int32_t baud_rate, int32_t flow_control);
int32_t ucx_system_SetUartSettings3(ucx_instance_t *inst, int32_t baud_rate, int32_t flow_control, int32_t change_after_confirm);
int32_t ucx_system_GetUartSettings(ucx_instance_t *inst, uCxSysGetUartSettings_t * pSysGetUartSettingsRsp);
int32_t ucx_system_GetLastErrorCode(ucx_instance_t *inst, int32_t * pErrorCode);
int32_t ucx_system_SetExtendedError(ucx_instance_t *inst, uSysExtendedErrors_t extended_errors);
int32_t ucx_system_GetExtendedError(ucx_instance_t *inst, uSysExtendedErrors_t * pExtendedErrors);
int32_t ucx_system_SetUnixTime(ucx_instance_t *inst, const uint8_t * unix_time, int32_t unix_time_len);
bool ucx_system_GetUnixTimeBegin(ucx_instance_t *inst, uByteArray_t * pUnixTime);
int32_t ucx_system_SetEchoOff(ucx_instance_t *inst);
int32_t ucx_system_SetEchoOn(ucx_instance_t *inst);
int32_t ucx_system_GetEcho(ucx_instance_t *inst, uSysEchoOn_t * pEchoOn);
int32_t ucx_system_SetEscSequenceChar(ucx_instance_t *inst, int32_t escape_char);
int32_t ucx_system_GetEscSequenceChar(ucx_instance_t *inst, int32_t * pEscapeChar);
int32_t ucx_system_SetLineTermChar(ucx_instance_t *inst, int32_t line_term);
int32_t ucx_system_GetLineTermChar(ucx_instance_t *inst, int32_t * pLineTerm);
int32_t ucx_system_SetRspFormatChar(ucx_instance_t *inst, int32_t resp_format);
int32_t ucx_system_GetRspFormatChar(ucx_instance_t *inst, int32_t * pRespFormat);
int32_t ucx_system_SetBackspaceChar(ucx_instance_t *inst, int32_t backspace);
int32_t ucx_system_GetBackspaceChar(ucx_instance_t *inst, int32_t * pBackspace);
int32_t ucx_system_SetEscSequenceSettings(ucx_instance_t *inst, int32_t pre_timeout, int32_t post_timeout, int32_t escape_timeout);
int32_t ucx_system_GetEscSequenceSettings(ucx_instance_t *inst, uCxSysGetEscSequenceSettings_t * pSysGetEscSequenceSettingsRsp);

/* ========== WIFI FUNCTIONS ========== */
int32_t ucx_wifi_SetHostname(ucx_instance_t *inst, const char * host_name);
bool ucx_wifi_GetHostnameBegin(ucx_instance_t *inst, const char * * ppHostName);
int32_t ucx_wifi_StationSetSecurityEnterprise5(ucx_instance_t *inst, int32_t wlan_handle, uWifiTlsVersion_t tls_version, const char * ca_name, const char * client_cert_name, const char * client_key_name);
int32_t ucx_wifi_StationSetSecurityEnterprise6(ucx_instance_t *inst, int32_t wlan_handle, uWifiTlsVersion_t tls_version, const char * ca_name, const char * client_cert_name, const char * client_key_name, const char * identity);
bool ucx_wifi_StationGetSecurityBegin(ucx_instance_t *inst, int32_t wlan_handle, uCxWifiStationGetSecurity_t * pWifiStationGetSecurityRsp);
int32_t ucx_wifi_StationSetSecurityPeap4(ucx_instance_t *inst, int32_t wlan_handle, uWifiTlsVersion_t tls_version, const char * peap_user, const char * peap_password);
int32_t ucx_wifi_StationSetSecurityPeap5(ucx_instance_t *inst, int32_t wlan_handle, uWifiTlsVersion_t tls_version, const char * peap_user, const char * peap_password, const char * ca_name);
int32_t ucx_wifi_StationSetSecurityWpa(ucx_instance_t *inst, int32_t wlan_handle, const char * passphrase, uWifiWpaThreshold_t wpa_threshold);
int32_t ucx_wifi_StationSetSecurityOpen(ucx_instance_t *inst, int32_t wlan_handle);
int32_t ucx_wifi_StationSetConnectionParams(ucx_instance_t *inst, int32_t wlan_handle, const char * ssid);
bool ucx_wifi_StationGetConnectionParamsBegin(ucx_instance_t *inst, int32_t wlan_handle, const char * * ppSsid);
int32_t ucx_wifi_StationSetIpConfigStatic4(ucx_instance_t *inst, int32_t wlan_handle, uSockIpAddress_t * ip_addr, uSockIpAddress_t * subnet_mask, uSockIpAddress_t * gateway);
int32_t ucx_wifi_StationSetIpConfigStatic5(ucx_instance_t *inst, int32_t wlan_handle, uSockIpAddress_t * ip_addr, uSockIpAddress_t * subnet_mask, uSockIpAddress_t * gateway, uSockIpAddress_t * prim_dns);
int32_t ucx_wifi_StationSetIpConfigStatic6(ucx_instance_t *inst, int32_t wlan_handle, uSockIpAddress_t * ip_addr, uSockIpAddress_t * subnet_mask, uSockIpAddress_t * gateway, uSockIpAddress_t * prim_dns, uSockIpAddress_t * sec_dns);
int32_t ucx_wifi_StationSetIpConfigDhcp(ucx_instance_t *inst, int32_t wlan_handle);
int32_t ucx_wifi_StationGetIpConfig(ucx_instance_t *inst, int32_t wlan_handle, uCxWifiStationGetIpConfig_t * pWifiStationGetIpConfigRsp);
int32_t ucx_wifi_StationConnect(ucx_instance_t *inst, int32_t wlan_handle);
int32_t ucx_wifi_StationDisconnect(ucx_instance_t *inst);
int32_t ucx_wifi_StationGetNetworkStatus(ucx_instance_t *inst, uWifiNetStatusId_t net_status_id, uSockIpAddress_t * pNetStatusVal);
void ucx_wifi_StationListNetworkStatusBegin(ucx_instance_t *inst);
bool ucx_wifi_StationListNetworkStatusGetNext(ucx_instance_t *inst, uCxWifiStationListNetworkStatus_t * pWifiStationListNetworkStatusRsp);
int32_t ucx_wifi_SetRegulatoryDomain(ucx_instance_t *inst, uWifiRegDomain_t reg_domain);
int32_t ucx_wifi_GetRegulatoryDomain(ucx_instance_t *inst, uWifiRegDomain_t * pRegDomain);
int32_t ucx_wifi_SetChannelList(ucx_instance_t *inst, const int16_t * channel_list, int32_t channel_list_len);
int32_t ucx_wifi_GetChannelList(ucx_instance_t *inst, uIntList_t * pChannelList);
int32_t ucx_wifi_GetActiveChannels(ucx_instance_t *inst, uIntList_t * pChannelList);
void ucx_wifi_StationScanDefaultBegin(ucx_instance_t *inst);
bool ucx_wifi_StationScanDefaultGetNext(ucx_instance_t *inst, uCxWifiStationScanDefault_t * pWifiStationScanDefaultRsp);
void ucx_wifi_StationScan1Begin(ucx_instance_t *inst, uWifiScanMode_t scan_mode);
bool ucx_wifi_StationScan1GetNext(ucx_instance_t *inst, uCxWifiStationScan_t * pWifiStationScanRsp);
void ucx_wifi_StationScan2Begin(ucx_instance_t *inst, uWifiScanMode_t scan_mode, const char * ssid);
bool ucx_wifi_StationScan2GetNext(ucx_instance_t *inst, uCxWifiStationScan_t * pWifiStationScanRsp);
bool ucx_wifi_StationStatusBegin(ucx_instance_t *inst, uWifiStatusId_t status_id, uCxWifiStationStatus_t * pWifiStationStatusRsp);
int32_t ucx_wifi_ApActivate(ucx_instance_t *inst);
int32_t ucx_wifi_ApDeactivate(ucx_instance_t *inst);
int32_t ucx_wifi_ApSetConnectionParams1(ucx_instance_t *inst, const char * ssid);
int32_t ucx_wifi_ApSetConnectionParams2(ucx_instance_t *inst, const char * ssid, uWifiChannel_t channel);
bool ucx_wifi_ApGetConnectionParamsBegin(ucx_instance_t *inst, uCxWifiApGetConnectionParams_t * pWifiApGetConnectionParamsRsp);
int32_t ucx_wifi_ApSetSecurityWpa1(ucx_instance_t *inst, const char * passphrase);
int32_t ucx_wifi_ApSetSecurityWpa2(ucx_instance_t *inst, const char * passphrase, uWifiWpaVersion_t wpa_version);
int32_t ucx_wifi_ApSetSecurityOpen(ucx_instance_t *inst);
int32_t ucx_wifi_ApGetSecurity(ucx_instance_t *inst, uCxWifiApGetSecurity_t * pWifiApGetSecurityRsp);
void ucx_wifi_ApListStationsBegin(ucx_instance_t *inst);
bool ucx_wifi_ApListStationsGetNext(ucx_instance_t *inst, uMacAddress_t * pMac);
int32_t ucx_wifi_ApGetNetworkStatus(ucx_instance_t *inst, uWifiNetStatusId_t net_status_id, uSockIpAddress_t * pNetStatusVal);
void ucx_wifi_ApListNetworkStatusBegin(ucx_instance_t *inst);
bool ucx_wifi_ApListNetworkStatusGetNext(ucx_instance_t *inst, uCxWifiApListNetworkStatus_t * pWifiApListNetworkStatusRsp);
int32_t ucx_wifi_SetWifiRoaming(ucx_instance_t *inst, uWifiRoaming_t roaming);
int32_t ucx_wifi_GetWifiRoaming(ucx_instance_t *inst, uWifiRoaming_t * pRoaming);
int32_t ucx_wifi_StationSetRoamingBGScanThreshold(ucx_instance_t *inst, int32_t roaming_scanning_threshold);
int32_t ucx_wifi_StationGetRoamingBGScanThreshold(ucx_instance_t *inst, int32_t * pRoamingScanningThreshold);
int32_t ucx_wifi_StationSetRoamingSwitchLimit(ucx_instance_t *inst, int32_t roaming_switch_limit);
int32_t ucx_wifi_StationGetRoamingSwitchLimit(ucx_instance_t *inst, int32_t * pRoamingSwitchLimit);
int32_t ucx_wifi_StationSetRoamingScanInterval(ucx_instance_t *inst, int32_t roaming_scan_interval);
int32_t ucx_wifi_StationGetRoamingScanInterval(ucx_instance_t *inst, int32_t * pRoamingScanInterval);
int32_t ucx_wifi_StationSetAggressiveRoaming(ucx_instance_t *inst, uWifiRoamingAggressive_t roaming_aggressive);
int32_t ucx_wifi_StationGetAggressiveRoaming(ucx_instance_t *inst, uWifiRoamingAggressive_t * pRoamingAggressive);
int32_t ucx_wifi_StationSetRoamingDelayMs(ucx_instance_t *inst, int32_t roaming_delay_time);
int32_t ucx_wifi_StationGetRoamingDelayMs(ucx_instance_t *inst, int32_t * pRoamingDelayTime);
int32_t ucx_wifi_StationSetRoamingAllChannels(ucx_instance_t *inst, uWifiRoamingChannels_t roaming_channels);
int32_t ucx_wifi_StationGetRoamingAllChannels(ucx_instance_t *inst, uWifiRoamingChannels_t * pRoamingChannels);
void ucx_wifi_RegisterLinkUp(ucx_instance_t *inst, uUEWLU_t callback);
void ucx_wifi_RegisterLinkDown(ucx_instance_t *inst, uUEWLD_t callback);
void ucx_wifi_RegisterStationNetworkUp(ucx_instance_t *inst, uUEWSNU_t callback);
void ucx_wifi_RegisterStationNetworkDown(ucx_instance_t *inst, uUEWSND_t callback);
void ucx_wifi_RegisterStationRoamingSwitchInitiated(ucx_instance_t *inst, uUEWSRSI_t callback);
void ucx_wifi_RegisterStationRoamingSwitchFailed(ucx_instance_t *inst, uUEWSRSF_t callback);
void ucx_wifi_RegisterStationRoamingSwitchCompleted(ucx_instance_t *inst, uUEWSRSC_t callback);
void ucx_wifi_RegisterApNetworkUp(ucx_instance_t *inst, uUEWAPNU_t callback);
void ucx_wifi_RegisterApNetworkDown(ucx_instance_t *inst, uUEWAPND_t callback);
void ucx_wifi_RegisterApUp(ucx_instance_t *inst, uUEWAPU_t callback);
void ucx_wifi_RegisterApDown(ucx_instance_t *inst, uUEWAPD_t callback);
void ucx_wifi_RegisterApStationAssociated(ucx_instance_t *inst, uUEWAPSA_t callback);
void ucx_wifi_RegisterApStationDisassociated(ucx_instance_t *inst, uUEWAPSDA_t callback);

#ifdef __cplusplus
}
#endif

#endif /* UCXCLIENT_WRAPPER_GENERATED_H */